
   
        document.addEventListener('DOMContentLoaded', function() {
            const quotes = [
                          // Life Quotes
            { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
            { quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
            { quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
            { quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
            { quote: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
            { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
            { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
            { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
            { quote: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
            { quote: "Get your facts first, then you can distort them as you please.", author: "Mark Twain" },
            { quote: "Life isn't about waiting for the storm to pass, it's about learning how to dance in the rain.", author: "Vivian Greene" },
            { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
            { quote: "Life is short, and it's up to you to make it sweet.", author: "Sarah Louise Delany" },
            { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
            { quote: "The unexamined life is not worth living.", author: "Socrates" },
            { quote: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
            { quote: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
            { quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
            { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
            { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
            { quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
            { quote: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
            { quote: "Life is a journey that must be traveled no matter how bad the roads and accommodations.", author: "Oliver Goldsmith" },
            { quote: "Life is either a great adventure or nothing.", author: "Helen Keller" },
            { quote: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
            { quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
            { quote: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
            { quote: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell" },
            { quote: "Everything has beauty, but not everyone can see.", author: "Confucius" },
            { quote: "Life is short, and it's up to you to make it sweet.", author: "Sarah Louise Delany" },
            { quote: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson" },
            { quote: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Anonymous" },
            { quote: "To live is to suffer, to survive is to find some meaning in the suffering.", author: "Friedrich Nietzsche" },
            { quote: "The most wasted of days is one without laughter.", author: "E.E. Cummings" },
            { quote: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
            { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
            { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
            { quote: "We do not remember days; we remember moments.", author: "Cesare Pavese" },
            { quote: "The most important thing is to enjoy your life—to be happy—it’s all that matters.", author: "Audre Lorde" },
            { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
            { quote: "Life is too important to be taken seriously.", author: "Oscar Wilde" },
            { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
            { quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
            { quote: "Life is not about waiting for the storm to pass, but learning to dance in the rain.", author: "Vivian Greene" },
            { quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
            { quote: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
            { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
            { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
            { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
            { quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
            { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
            { quote: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
            { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
            { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
            { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
            { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
            { quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
            { quote: "The best way to predict your future is to create it.", author: "Peter Drucker" },
            { quote: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
            { quote: "To live is to suffer, to survive is to find some meaning in the suffering.", author: "Friedrich Nietzsche" },
            { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
            { quote: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
            { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
            { quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
            { quote: "We do not remember days, we remember moments.", author: "Cesare Pavese" },
            { quote: "The greatest wealth is to live content with little.", author: "Plato" },
            { quote: "The secret of happiness is freedom, and the secret of freedom is courage.", author: "Thucydides" },
            { quote: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
            { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
            { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
            { quote: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
            { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
            { quote: "Life is too short to be small.", author: "Benjamin Disraeli" },
            { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
            { quote: "Happiness depends upon ourselves.", author: "Aristotle" },
            { quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
            { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
            { quote: "The best way to predict the future is to invent it.", author: "Alan Kay" },
            { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
            { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
            { quote: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
            // Job Searching Quotes
            { quote: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
            { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
            { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
            { quote: "The future depends on what you do today.", author: "Mahatma Gandhi" },
            { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
            { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
            { quote: "The best way to predict your future is to create it.", author: "Peter Drucker" },
            { quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
            { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
            { quote: "Hard work beats talent when talent doesn't work hard.", author: "Kevin Durant" },
            { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
            { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
            { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
            { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
            { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
            { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
            { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
            { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
            { quote: "Success is not just about making money. It’s about making a difference.", author: "Unknown" },
            { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
            { quote: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
            { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
            { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
            { quote: "The future depends on what you do today.", author: "Mahatma Gandhi" },
            { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
            { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
            { quote: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
            { quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
            { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
            { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
            { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
            { quote: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
            { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
            { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
            { quote: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
            // Quotes from Indian Sources
            { quote: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
            { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
            { quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Herman Cain" },
            { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
            { quote: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
            { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
            { quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
            { quote: "Happiness depends upon ourselves.", author: "Aristotle" },
            { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
            { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
            { quote: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
            { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
            { quote: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
            { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
            { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
            { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
            { quote: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
            { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
            { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
            { quote: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
            { quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
            { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
            { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
            { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
            // Quotes from Virat Kohli
            { quote: "Self-belief and hard work will always earn you success.", author: "Virat Kohli" },
            { quote: "I have always believed that if you put in the work, the results will come.", author: "Virat Kohli" },
            { quote: "A champion is someone who gets up when they can't.", author: "Virat Kohli" },
            { quote: "You can’t always control what goes on outside. But you can always control what goes on inside.", author: "Virat Kohli" },
            { quote: "If you have the passion and dedication, you will reach where you want to.", author: "Virat Kohli" },
            { quote: "Dreams do come true if you stay focused and work hard.", author: "Virat Kohli" },
            // Quotes from Rohit Sharma
            { quote: "The more you practice, the more confident you become.", author: "Rohit Sharma" },
            { quote: "You have to keep working hard and stay focused on your goals.", author: "Rohit Sharma" },
            { quote: "Consistency is key to achieving your goals.", author: "Rohit Sharma" },
            { quote: "Believe in yourself, and the rest will follow.", author: "Rohit Sharma" },
            { quote: "Hard work and dedication are the cornerstones of success.", author: "Rohit Sharma" },
            { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Rohit Sharma" },
          
            ];
        
            // Get a random quote
            const randomIndex = Math.floor(Math.random() * quotes.length);
            const randomQuote = quotes[randomIndex];
        
            // Display the quote and author in the modal
            document.getElementById("modal-quote").innerText = `"${randomQuote.quote}"`;
            document.getElementById("modal-author").innerText = `- ${randomQuote.author}`;
        
            // Show the modal
            const myModal = new bootstrap.Modal(document.getElementById('quoteModal'));
            myModal.show();
        });